================================= REPORT CSV FLUSH ====================================
id, id_type, name, whamm_type, wasm_type, script_id, fname, fid, pc, probe_id, value(s)
4, memaddr, val, i32, i32, script0, main, 0, 3, 52_wasm:opcode:i64.const, 0
36, memaddr, val1, i32, i32, script0, main, 0, 3, 52_wasm:opcode:i64.const, 0
68, memaddr, val, i32, i32, script0, main, 0, 5, 41_wasm:opcode:i64.store, 1
100, memaddr, val1, i32, i32, script0, main, 0, 5, 41_wasm:opcode:i64.store, 0
132, memaddr, val, i32, i32, script0, main, 0, 8, 51_wasm:opcode:i32.const, 2
164, memaddr, val1, i32, i32, script0, main, 0, 8, 51_wasm:opcode:i32.const, 0
196, memaddr, val, i32, i32, script0, main, 0, 10, 26_wasm:opcode:i32.load, 3
228, memaddr, val1, i32, i32, script0, main, 0, 10, 26_wasm:opcode:i32.load, 0
260, memaddr, val, i32, i32, script0, main, 0, 13, 26_wasm:opcode:i32.load, 4
292, memaddr, val1, i32, i32, script0, main, 0, 13, 26_wasm:opcode:i32.load, 0
324, memaddr, val, i32, i32, script0, main, 0, 16, 18_wasm:opcode:drop, 5
356, memaddr, val1, i32, i32, script0, main, 0, 16, 18_wasm:opcode:drop, 0
388, memaddr, val, i32, i32, script0, main, 0, 17, 9_wasm:opcode:end, 6
420, memaddr, val1, i32, i32, script0, main, 0, 17, 9_wasm:opcode:end, 0