================================= REPORT CSV FLUSH ====================================
id, id_type, name, whamm_type, wasm_type, script_id, fname, fid, pc, probe_id, value(s)
72, memaddr, length, u32, i32, script0, main, 5, 47, 0_wasm:opcode:drop, 27
300, memaddr, length, u32, i32, script0, main, 5, 52, 0_wasm:opcode:drop, 27
528, memaddr, length, u32, i32, script0, main, 5, 57, 0_wasm:opcode:drop, 27
756, memaddr, length, u32, i32, script0, main, 5, 62, 0_wasm:opcode:drop, 27
984, memaddr, length, u32, i32, script0, main, 5, 67, 0_wasm:opcode:drop, 27
4, memaddr, l, i32, i32, script0, main, 5, 47, 0_wasm:opcode:drop, 27
232, memaddr, l, i32, i32, script0, main, 5, 52, 0_wasm:opcode:drop, 27
460, memaddr, l, i32, i32, script0, main, 5, 57, 0_wasm:opcode:drop, 27
688, memaddr, l, i32, i32, script0, main, 5, 62, 0_wasm:opcode:drop, 27
916, memaddr, l, i32, i32, script0, main, 5, 67, 0_wasm:opcode:drop, 27
104, memaddr, start_exp_true, bool, i32, script0, main, 5, 47, 0_wasm:opcode:drop, true
136, memaddr, start_exp_false, bool, i32, script0, main, 5, 47, 0_wasm:opcode:drop, false
168, memaddr, end_exp_true, bool, i32, script0, main, 5, 47, 0_wasm:opcode:drop, true
200, memaddr, end_exp_false, bool, i32, script0, main, 5, 47, 0_wasm:opcode:drop, false
332, memaddr, start_exp_true, bool, i32, script0, main, 5, 52, 0_wasm:opcode:drop, true
364, memaddr, start_exp_false, bool, i32, script0, main, 5, 52, 0_wasm:opcode:drop, false
396, memaddr, end_exp_true, bool, i32, script0, main, 5, 52, 0_wasm:opcode:drop, true
428, memaddr, end_exp_false, bool, i32, script0, main, 5, 52, 0_wasm:opcode:drop, false
560, memaddr, start_exp_true, bool, i32, script0, main, 5, 57, 0_wasm:opcode:drop, true
592, memaddr, start_exp_false, bool, i32, script0, main, 5, 57, 0_wasm:opcode:drop, false
624, memaddr, end_exp_true, bool, i32, script0, main, 5, 57, 0_wasm:opcode:drop, true
656, memaddr, end_exp_false, bool, i32, script0, main, 5, 57, 0_wasm:opcode:drop, false
788, memaddr, start_exp_true, bool, i32, script0, main, 5, 62, 0_wasm:opcode:drop, true
820, memaddr, start_exp_false, bool, i32, script0, main, 5, 62, 0_wasm:opcode:drop, false
852, memaddr, end_exp_true, bool, i32, script0, main, 5, 62, 0_wasm:opcode:drop, true
884, memaddr, end_exp_false, bool, i32, script0, main, 5, 62, 0_wasm:opcode:drop, false
1016, memaddr, start_exp_true, bool, i32, script0, main, 5, 67, 0_wasm:opcode:drop, true
1048, memaddr, start_exp_false, bool, i32, script0, main, 5, 67, 0_wasm:opcode:drop, false
1080, memaddr, end_exp_true, bool, i32, script0, main, 5, 67, 0_wasm:opcode:drop, true
1112, memaddr, end_exp_false, bool, i32, script0, main, 5, 67, 0_wasm:opcode:drop, false
36, memaddr, s, str, (i32, i32), script0, main, 5, 47, 0_wasm:opcode:drop, abcdefghijklmnopqrstuvwxyz

264, memaddr, s, str, (i32, i32), script0, main, 5, 52, 0_wasm:opcode:drop, abcdefghijklmnopqrstuvwxyz

492, memaddr, s, str, (i32, i32), script0, main, 5, 57, 0_wasm:opcode:drop, abcdefghijklmnopqrstuvwxyz

720, memaddr, s, str, (i32, i32), script0, main, 5, 62, 0_wasm:opcode:drop, abcdefghijklmnopqrstuvwxyz

948, memaddr, s, str, (i32, i32), script0, main, 5, 67, 0_wasm:opcode:drop, abcdefghijklmnopqrstuvwxyz