================================= REPORT CSV FLUSH ====================================
id, id_type, name, whamm_type, wasm_type, script_id, fname, fid, pc, probe_id, value(s)
4, memaddr, num, i32, i32, script0, basic_br, 0, 0, 0_wasm:func:entry, 1
36, memaddr, num, i32, i32, script0, if_stmt, 3, 0, 1_wasm:func:entry, 2
68, memaddr, num, i32, i32, script0, if_stmt, 3, 0, 3_wasm:func:entry, 4
100, memaddr, num, i32, i32, script0, select_stmt, 4, 0, 1_wasm:func:entry, 2
132, memaddr, num, i32, i32, script0, select_stmt, 4, 0, 2_wasm:func:entry, 3

