// Breadth-test script generator.
//
// Walks the provider/package/event/mode IR built from `providers/*.yaml` and emits two
// .mm scripts that each declare a probe for every targetable site:
//
//   * `breadth.mm`     -> probes whose bodies declare every non-engine_only bound item.
//   * `breadth_wei.mm` -> probes whose bodies declare every engine_only bound item.
//
// Both scripts are checked in. The `regenerates_match_disk` test below diffs the
// freshly-walked output against the on-disk files so that any change to a provider yaml
// without a corresponding regeneration trips CI.
//
// Regenerate after editing a provider yaml:
//     WHAMM_BREADTH_REGEN=1 cargo test --test main breadth::gen

use std::fs;
use std::path::PathBuf;

use whamm::parser::provider_handler::{
    yml_to_providers, BoundFunc, BoundVar, EventDef, ModeDef, ModeKind, PackageDef, ProviderDef,
};
use whamm::parser::types::{DataType, Expr};
use whamm::parser::yml_processor::pull_all_yml_files;

const HEADER: &str = "// AUTO-GENERATED by tests/breadth/gen.rs. Do not edit by hand.\n\
     // Regenerate: WHAMM_BREADTH_REGEN=1 cargo test --test main breadth::gen\n\n";

const PATTERN_MARKER: &str = "[0:9]+";

pub(crate) fn breadth_path() -> PathBuf {
    PathBuf::from("tests/breadth/breadth.mm")
}
pub(crate) fn breadth_wei_path() -> PathBuf {
    PathBuf::from("tests/breadth/breadth_wei.mm")
}

#[test]
fn regenerates_match_disk() {
    let (regular, engine_only) = generate();
    let regen = std::env::var("WHAMM_BREADTH_REGEN").is_ok();

    if regen {
        fs::write(breadth_path(), &regular).expect("write breadth.mm");
        fs::write(breadth_wei_path(), &engine_only).expect("write breadth_wei.mm");
        return;
    }

    let on_disk_regular = fs::read_to_string(breadth_path()).unwrap_or_default();
    let on_disk_engine = fs::read_to_string(breadth_wei_path()).unwrap_or_default();

    if on_disk_regular != regular || on_disk_engine != engine_only {
        panic!(
            "breadth scripts are stale. Re-run with WHAMM_BREADTH_REGEN=1 to refresh \
             tests/breadth/breadth.mm and tests/breadth/breadth_wei.mm."
        );
    }
}

fn generate() -> (String, String) {
    let yamls = pull_all_yml_files("./");
    let providers = match yml_to_providers(&yamls) {
        Ok(p) => p,
        Err(e) => panic!(
            "parse provider yamls failed: {} error(s)",
            e.pull_errs().len()
        ),
    };

    let mut out = Output {
        regular: String::from(HEADER),
        engine_only: String::from(HEADER),
    };

    for provider in providers.iter() {
        walk_provider(provider, &mut out);
    }

    (out.regular, out.engine_only)
}

/// Output buffers we accumulate into — one per generated script.
struct Output {
    regular: String,
    engine_only: String,
}

/// Bound vars and fns declared at a single hierarchy level (provider, package, or event).
#[derive(Clone, Copy)]
struct BoundItems<'a> {
    vars: &'a [BoundVar],
    fns: &'a [BoundFunc],
}

const EMPTY: BoundItems<'static> = BoundItems {
    vars: &[],
    fns: &[],
};

/// Identifies the probe site we're about to emit. `package`/`event`/`mode` are `None`
/// when the corresponding YAML segment doesn't apply (e.g. `wasm:begin` has no event).
struct RuleSite<'a> {
    provider: &'a str,
    package: Option<&'a str>,
    event: Option<&'a str>,
    mode: Option<&'a ModeDef>,
}

fn walk_provider(provider: &ProviderDef, out: &mut Output) {
    let prov = BoundItems {
        vars: &provider.def.bound_vars,
        fns: &provider.def.bound_fns,
    };

    if provider.packages.is_empty() {
        emit_probe(
            &RuleSite {
                provider: &provider.def.name,
                package: None,
                event: None,
                mode: None,
            },
            &merge(prov, EMPTY, EMPTY),
            out,
        );
        return;
    }

    for package in provider.packages.iter() {
        walk_package(provider, package, prov, out);
    }
}

fn walk_package(
    provider: &ProviderDef,
    package: &PackageDef,
    prov: BoundItems<'_>,
    out: &mut Output,
) {
    let pkg = BoundItems {
        vars: &package.def.bound_vars,
        fns: &package.def.bound_fns,
    };

    if package.events.is_empty() {
        emit_probe(
            &RuleSite {
                provider: &provider.def.name,
                package: Some(&package.def.name),
                event: None,
                mode: None,
            },
            &merge(prov, pkg, EMPTY),
            out,
        );
        return;
    }

    for event in package.events.iter() {
        walk_event(provider, package, event, prov, pkg, out);
    }
}

fn walk_event(
    provider: &ProviderDef,
    package: &PackageDef,
    event: &EventDef,
    prov: BoundItems<'_>,
    pkg: BoundItems<'_>,
    out: &mut Output,
) {
    let evt = BoundItems {
        vars: &event.def.bound_vars,
        fns: &event.def.bound_fns,
    };
    let in_scope = merge(prov, pkg, evt);

    if event.modes.is_empty() {
        emit_probe(
            &RuleSite {
                provider: &provider.def.name,
                package: Some(&package.def.name),
                event: Some(&event.def.name),
                mode: None,
            },
            &in_scope,
            out,
        );
        return;
    }

    for mode in event.modes.iter() {
        emit_probe(
            &RuleSite {
                provider: &provider.def.name,
                package: Some(&package.def.name),
                event: Some(&event.def.name),
                mode: Some(mode),
            },
            &in_scope,
            out,
        );
    }
}

fn emit_probe(site: &RuleSite<'_>, in_scope: &AllBoundItems<'_>, out: &mut Output) {
    let rule = build_rule(site);

    let (vars_regular, vars_engine): (Vec<&BoundVar>, Vec<&BoundVar>) =
        in_scope.vars.iter().partition(|v| !v.engine_only);
    let (fns_regular, fns_engine): (Vec<&BoundFunc>, Vec<&BoundFunc>) =
        in_scope.fns.iter().partition(|f| !f.engine_only);

    let body_regular = build_body(&vars_regular, &fns_regular);
    let body_engine = build_body(&vars_engine, &fns_engine);

    out.regular.push_str(&format_probe(&rule, &body_regular));
    out.engine_only.push_str(&format_probe(&rule, &body_engine));
}

/// All bound vars/fns in scope at a probe site (provider + package + event levels).
struct AllBoundItems<'a> {
    vars: Vec<&'a BoundVar>,
    fns: Vec<&'a BoundFunc>,
}

fn merge<'a>(prov: BoundItems<'a>, pkg: BoundItems<'a>, evt: BoundItems<'a>) -> AllBoundItems<'a> {
    AllBoundItems {
        vars: prov.vars.iter().chain(pkg.vars).chain(evt.vars).collect(),
        fns: prov.fns.iter().chain(pkg.fns).chain(evt.fns).collect(),
    }
}

fn format_probe(rule: &str, body: &str) -> String {
    if body.is_empty() {
        format!("{rule} {{ }}\n\n")
    } else {
        format!("{rule} {{\n{body}}}\n\n")
    }
}

fn build_rule(site: &RuleSite<'_>) -> String {
    let mut parts = vec![site.provider.to_string()];
    if let Some(pkg) = site.package {
        parts.push(pkg.to_string());
    }
    if let Some(evt) = site.event {
        if !evt.is_empty() {
            parts.push(evt.to_string());
        }
    }
    if let Some(m) = site.mode {
        if !matches!(m.kind, ModeKind::Null) {
            // Use the alias when present (e.g. semantic_after may be aliased)
            let name = m.alias.clone().unwrap_or_else(|| m.def.name.clone());
            parts.push(name);
        }
    }
    parts.join(":")
}

fn build_body(vars: &[&BoundVar], fns: &[&BoundFunc]) -> String {
    let mut lines = String::new();
    let mut idx = 0usize;

    for var in vars {
        let name = materialize_pattern_name(&var.name);
        let ty = breadth_type(&var.ty);
        lines.push_str(&format!("    var v{idx}: {ty} = {name};\n"));
        idx += 1;
    }

    for f in fns {
        let Some(args) = synth_args(&f.func.params) else {
            continue;
        };
        let fname = &f.func.name.name;
        if returns_unit(&f.func.results) {
            lines.push_str(&format!("    {fname}({args});\n"));
        } else {
            let ret = breadth_type(&f.func.results);
            lines.push_str(&format!("    var v{idx}: {ret} = {fname}({args});\n"));
            idx += 1;
        }
    }

    lines
}

// `localN`/`argN`/`resN`/`immN` are pattern names that match any index — for the breadth
// probes we just reference the singleton `local0`/`arg0`/`res0`/`imm0`.
fn materialize_pattern_name(name: &str) -> String {
    if let Some(stem) = name.strip_suffix(PATTERN_MARKER) {
        format!("{stem}0")
    } else {
        name.to_string()
    }
}

// Per agreed convention: `Unknown` collapses to `i32` for the breadth tests, since this
// suite is about parity of bound-item exposure, not type correctness (covered elsewhere).
fn breadth_type(ty: &DataType) -> String {
    match ty {
        DataType::Unknown => "i32".to_string(),
        other => other.to_string(),
    }
}

fn returns_unit(ty: &DataType) -> bool {
    matches!(ty, DataType::Tuple { ty_info } if ty_info.is_empty())
}

fn synth_args(params: &[(Expr, DataType)]) -> Option<String> {
    let mut out = Vec::with_capacity(params.len());
    for (_, ty) in params {
        out.push(synth_literal(ty)?);
    }
    Some(out.join(", "))
}

fn synth_literal(ty: &DataType) -> Option<String> {
    Some(match ty {
        DataType::U8
        | DataType::I8
        | DataType::U16
        | DataType::I16
        | DataType::U32
        | DataType::I32
        | DataType::U64
        | DataType::I64
        | DataType::Unknown => format!("0 as {}", breadth_type(ty)),
        DataType::F32 | DataType::F64 => format!("0.0 as {}", ty),
        DataType::Boolean => "false".to_string(),
        DataType::Str => "\"\"".to_string(),
        DataType::FuncRef
        | DataType::Tuple { .. }
        | DataType::Map { .. }
        | DataType::Lib
        | DataType::Null
        | DataType::AssumeGood => return None,
    })
}
