
================================= REPORT CSV FLUSH ====================================
id, id_type, name, whamm_type, wasm_type, script_id, fname, fid, pc, probe_id, value(s)
4, memaddr, resolved, i32, i32, script0, _start, 5, 1, 0_wasm:opcode:ref.func:before, 0
36, memaddr, resolved, i32, i32, script0, _start, 5, 4, 0_wasm:opcode:ref.func:before, 1
68, memaddr, resolved, i32, i32, script0, _start, 5, 7, 0_wasm:opcode:ref.func:before, 2
100, memaddr, resolved, i32, i32, script0, _start, 5, 22, 0_wasm:opcode:ref.func:before, 3
132, memaddr, resolved, i32, i32, script0, _start, 5, 26, 0_wasm:opcode:ref.func:before, 0
164, memaddr, resolved, i32, i32, script0, _start, 5, 40, 0_wasm:opcode:ref.func:before, 1
