================================= REPORT CSV FLUSH ====================================
id, id_type, name, whamm_type, wasm_type, script_id, fname, fid, pc, probe_id, value(s)
4, memaddr, resolved, i32, i32, script0, #5, 5, 3, 0_wasm:opcode:call_indirect:before, 0
36, memaddr, resolved, i32, i32, script0, #5, 5, 15, 0_wasm:opcode:call_indirect:before, 3
68, memaddr, resolved, i32, i32, script0, #5, 5, 25, 0_wasm:opcode:call_indirect:before, -1
100, memaddr, resolved, i32, i32, script0, #5, 5, 41, 0_wasm:opcode:call_indirect:before, 3
132, memaddr, resolved, i32, i32, script0, #5, 5, 47, 0_wasm:opcode:call_indirect:before, -1
164, memaddr, resolved, i32, i32, script0, #5, 5, 62, 0_wasm:opcode:call_indirect:before, -1
196, memaddr, resolved, i32, i32, script0, #5, 5, 78, 0_wasm:opcode:call_indirect:before, -1
