
================================= REPORT CSV FLUSH ====================================
id, id_type, name, whamm_type, wasm_type, script_id, fname, fid, pc, probe_id, value(s)
4, memaddr, resolved, i32, i32, script0, f, 0, 15, 0_wasm:opcode:call_indirect:before, 0
36, memaddr, resolved, i32, i32, script0, tail_caller, 2, 5, 1_wasm:opcode:return_call_indirect:before, 1
68, memaddr, resolved, i32, i32, script0, _start, 3, 5, 0_wasm:opcode:call_indirect:before, 0
