================================= REPORT CSV FLUSH ====================================
id, id_type, name, whamm_type, wasm_type, script_id, fname, fid, pc, probe_id, value(s)
360, memaddr, t11, i32, i32, script0, _start, 5, 9, 0_wasm:opcode:call, 997
464, memaddr, c, i32, i32, script0, _start, 5, 9, 0_wasm:opcode:call, 12
924, memaddr, t11, i32, i32, script0, _start, 5, 18, 0_wasm:opcode:call, 997
1028, memaddr, c, i32, i32, script0, _start, 5, 18, 0_wasm:opcode:call, 12
1488, memaddr, t11, i32, i32, script0, _start, 5, 27, 0_wasm:opcode:call, 997
1592, memaddr, c, i32, i32, script0, _start, 5, 27, 0_wasm:opcode:call, 12
2052, memaddr, t11, i32, i32, script0, _start, 5, 36, 0_wasm:opcode:call, 997
2156, memaddr, c, i32, i32, script0, _start, 5, 36, 0_wasm:opcode:call, 12
2616, memaddr, t11, i32, i32, script0, _start, 5, 45, 0_wasm:opcode:call, 997
2720, memaddr, c, i32, i32, script0, _start, 5, 45, 0_wasm:opcode:call, 12
3180, memaddr, t11, i32, i32, script0, _start, 5, 50, 0_wasm:opcode:call, 997
3284, memaddr, c, i32, i32, script0, _start, 5, 50, 0_wasm:opcode:call, 12
3744, memaddr, t11, i32, i32, script0, _start, 5, 55, 0_wasm:opcode:call, 997
3848, memaddr, c, i32, i32, script0, _start, 5, 55, 0_wasm:opcode:call, 12
4308, memaddr, t11, i32, i32, script0, _start, 5, 60, 0_wasm:opcode:call, 997
4412, memaddr, c, i32, i32, script0, _start, 5, 60, 0_wasm:opcode:call, 12
4872, memaddr, t11, i32, i32, script0, _start, 5, 65, 0_wasm:opcode:call, 997
4976, memaddr, c, i32, i32, script0, _start, 5, 65, 0_wasm:opcode:call, 12
392, memaddr, t12, bool, i32, script0, _start, 5, 9, 0_wasm:opcode:call, true
956, memaddr, t12, bool, i32, script0, _start, 5, 18, 0_wasm:opcode:call, true
1520, memaddr, t12, bool, i32, script0, _start, 5, 27, 0_wasm:opcode:call, true
2084, memaddr, t12, bool, i32, script0, _start, 5, 36, 0_wasm:opcode:call, true
2648, memaddr, t12, bool, i32, script0, _start, 5, 45, 0_wasm:opcode:call, true
3212, memaddr, t12, bool, i32, script0, _start, 5, 50, 0_wasm:opcode:call, true
3776, memaddr, t12, bool, i32, script0, _start, 5, 55, 0_wasm:opcode:call, true
4340, memaddr, t12, bool, i32, script0, _start, 5, 60, 0_wasm:opcode:call, true
4904, memaddr, t12, bool, i32, script0, _start, 5, 65, 0_wasm:opcode:call, true
424, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 9, 0_wasm:opcode:call, (1; (12; 13))
988, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 18, 0_wasm:opcode:call, (1; (12; 13))
1552, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 27, 0_wasm:opcode:call, (1; (12; 13))
2116, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 36, 0_wasm:opcode:call, (1; (12; 13))
2680, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 45, 0_wasm:opcode:call, (1; (12; 13))
3244, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 50, 0_wasm:opcode:call, (1; (12; 13))
3808, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 55, 0_wasm:opcode:call, (1; (12; 13))
4372, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 60, 0_wasm:opcode:call, (1; (12; 13))
4936, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 65, 0_wasm:opcode:call, (1; (12; 13))
4, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 9, 0_wasm:opcode:call, (0; 1; 2)
44, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 9, 0_wasm:opcode:call, (0; 1; 2)
202, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 9, 0_wasm:opcode:call, (0; 1; 2)
568, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 18, 0_wasm:opcode:call, (0; 1; 2)
608, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 18, 0_wasm:opcode:call, (0; 1; 2)
766, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 18, 0_wasm:opcode:call, (0; 1; 2)
1132, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 27, 0_wasm:opcode:call, (0; 1; 2)
1172, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 27, 0_wasm:opcode:call, (0; 1; 2)
1330, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 27, 0_wasm:opcode:call, (0; 1; 2)
1696, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 36, 0_wasm:opcode:call, (0; 1; 2)
1736, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 36, 0_wasm:opcode:call, (0; 1; 2)
1894, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 36, 0_wasm:opcode:call, (0; 1; 2)
2260, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 45, 0_wasm:opcode:call, (0; 1; 2)
2300, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 45, 0_wasm:opcode:call, (0; 1; 2)
2458, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 45, 0_wasm:opcode:call, (0; 1; 2)
2824, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 50, 0_wasm:opcode:call, (0; 1; 2)
2864, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 50, 0_wasm:opcode:call, (0; 1; 2)
3022, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 50, 0_wasm:opcode:call, (0; 1; 2)
3388, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 55, 0_wasm:opcode:call, (0; 1; 2)
3428, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 55, 0_wasm:opcode:call, (0; 1; 2)
3586, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 55, 0_wasm:opcode:call, (0; 1; 2)
3952, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 60, 0_wasm:opcode:call, (0; 1; 2)
3992, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 60, 0_wasm:opcode:call, (0; 1; 2)
4150, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 60, 0_wasm:opcode:call, (0; 1; 2)
4516, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 65, 0_wasm:opcode:call, (0; 1; 2)
4556, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 65, 0_wasm:opcode:call, (0; 1; 2)
4714, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 65, 0_wasm:opcode:call, (0; 1; 2)
532, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 9, 0_wasm:opcode:call, (0; 9)
1096, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 18, 0_wasm:opcode:call, (1; 18)
1660, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 27, 0_wasm:opcode:call, (1; 27)
2224, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 36, 0_wasm:opcode:call, (3; 36)
2788, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 45, 0_wasm:opcode:call, (0; 45)
3352, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 50, 0_wasm:opcode:call, (1; 50)
3916, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 55, 0_wasm:opcode:call, (2; 55)
4480, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 60, 0_wasm:opcode:call, (0; 60)
5044, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 65, 0_wasm:opcode:call, (0; 65)
125, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 9, 0_wasm:opcode:call, (-10; other str)
283, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 9, 0_wasm:opcode:call, (-5; wassup)
689, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 18, 0_wasm:opcode:call, (-10; other str)
847, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 18, 0_wasm:opcode:call, (-5; wassup)
1253, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 27, 0_wasm:opcode:call, (-10; other str)
1411, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 27, 0_wasm:opcode:call, (-5; wassup)
1817, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 36, 0_wasm:opcode:call, (-10; other str)
1975, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 36, 0_wasm:opcode:call, (-5; wassup)
2381, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 45, 0_wasm:opcode:call, (-10; other str)
2539, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 45, 0_wasm:opcode:call, (-5; wassup)
2945, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 50, 0_wasm:opcode:call, (-10; other str)
3103, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 50, 0_wasm:opcode:call, (-5; wassup)
3509, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 55, 0_wasm:opcode:call, (-10; other str)
3667, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 55, 0_wasm:opcode:call, (-5; wassup)
4073, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 60, 0_wasm:opcode:call, (-10; other str)
4231, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 60, 0_wasm:opcode:call, (-5; wassup)
4637, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 65, 0_wasm:opcode:call, (-10; other str)
4795, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 65, 0_wasm:opcode:call, (-5; wassup)
162, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 9, 0_wasm:opcode:call, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
320, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 9, 0_wasm:opcode:call, (wassup; +1.00018e3)
726, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 18, 0_wasm:opcode:call, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
884, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 18, 0_wasm:opcode:call, (wassup; +1.00018e3)
1290, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 27, 0_wasm:opcode:call, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
1448, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 27, 0_wasm:opcode:call, (wassup; +1.00018e3)
1854, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 36, 0_wasm:opcode:call, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
2012, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 36, 0_wasm:opcode:call, (wassup; +1.00018e3)
2418, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 45, 0_wasm:opcode:call, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
2576, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 45, 0_wasm:opcode:call, (wassup; +1.00018e3)
2982, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 50, 0_wasm:opcode:call, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
3140, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 50, 0_wasm:opcode:call, (wassup; +1.00018e3)
3546, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 55, 0_wasm:opcode:call, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
3704, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 55, 0_wasm:opcode:call, (wassup; +1.00018e3)
4110, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 60, 0_wasm:opcode:call, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
4268, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 60, 0_wasm:opcode:call, (wassup; +1.00018e3)
4674, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 65, 0_wasm:opcode:call, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
4832, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 65, 0_wasm:opcode:call, (wassup; +1.00018e3)
496, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 9, 0_wasm:opcode:call, (5; 9)
1060, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 18, 0_wasm:opcode:call, (5; 18)
1624, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 27, 0_wasm:opcode:call, (5; 27)
2188, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 36, 0_wasm:opcode:call, (5; 36)
2752, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 45, 0_wasm:opcode:call, (5; 45)
3316, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 50, 0_wasm:opcode:call, (5; 50)
3880, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 55, 0_wasm:opcode:call, (5; 55)
4444, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 60, 0_wasm:opcode:call, (5; 60)
5008, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 65, 0_wasm:opcode:call, (5; 65)
84, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 9, 0_wasm:opcode:call, (0; 1; -2)
242, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 9, 0_wasm:opcode:call, (0; 1; 2)
648, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 18, 0_wasm:opcode:call, (0; 1; -2)
806, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 18, 0_wasm:opcode:call, (0; 1; 2)
1212, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 27, 0_wasm:opcode:call, (0; 1; -2)
1370, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 27, 0_wasm:opcode:call, (0; 1; 2)
1776, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 36, 0_wasm:opcode:call, (0; 1; -2)
1934, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 36, 0_wasm:opcode:call, (0; 1; 2)
2340, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 45, 0_wasm:opcode:call, (0; 1; -2)
2498, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 45, 0_wasm:opcode:call, (0; 1; 2)
2904, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 50, 0_wasm:opcode:call, (0; 1; -2)
3062, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 50, 0_wasm:opcode:call, (0; 1; 2)
3468, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 55, 0_wasm:opcode:call, (0; 1; -2)
3626, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 55, 0_wasm:opcode:call, (0; 1; 2)
4032, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 60, 0_wasm:opcode:call, (0; 1; -2)
4190, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 60, 0_wasm:opcode:call, (0; 1; 2)
4596, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 65, 0_wasm:opcode:call, (0; 1; -2)
4754, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 65, 0_wasm:opcode:call, (0; 1; 2)