
================================= REPORT CSV FLUSH ====================================
id, id_type, name, whamm_type, wasm_type, script_id, fname, fid, pc, probe_id, value(s)
4, memaddr, t11, i32, i32, script0, _start, 5, 9, 0_wasm:opcode:call:before, 997
36, memaddr, c, i32, i32, script0, _start, 5, 9, 0_wasm:opcode:call:before, 12
568, memaddr, t11, i32, i32, script0, _start, 5, 18, 0_wasm:opcode:call:before, 997
600, memaddr, c, i32, i32, script0, _start, 5, 18, 0_wasm:opcode:call:before, 12
1132, memaddr, t11, i32, i32, script0, _start, 5, 27, 0_wasm:opcode:call:before, 997
1164, memaddr, c, i32, i32, script0, _start, 5, 27, 0_wasm:opcode:call:before, 12
1696, memaddr, t11, i32, i32, script0, _start, 5, 36, 0_wasm:opcode:call:before, 997
1728, memaddr, c, i32, i32, script0, _start, 5, 36, 0_wasm:opcode:call:before, 12
2260, memaddr, t11, i32, i32, script0, _start, 5, 45, 0_wasm:opcode:call:before, 997
2292, memaddr, c, i32, i32, script0, _start, 5, 45, 0_wasm:opcode:call:before, 12
2824, memaddr, t11, i32, i32, script0, _start, 5, 50, 0_wasm:opcode:call:before, 997
2856, memaddr, c, i32, i32, script0, _start, 5, 50, 0_wasm:opcode:call:before, 12
3388, memaddr, t11, i32, i32, script0, _start, 5, 55, 0_wasm:opcode:call:before, 997
3420, memaddr, c, i32, i32, script0, _start, 5, 55, 0_wasm:opcode:call:before, 12
3952, memaddr, t11, i32, i32, script0, _start, 5, 60, 0_wasm:opcode:call:before, 997
3984, memaddr, c, i32, i32, script0, _start, 5, 60, 0_wasm:opcode:call:before, 12
4516, memaddr, t11, i32, i32, script0, _start, 5, 65, 0_wasm:opcode:call:before, 997
4548, memaddr, c, i32, i32, script0, _start, 5, 65, 0_wasm:opcode:call:before, 12
68, memaddr, t12, bool, i32, script0, _start, 5, 9, 0_wasm:opcode:call:before, true
632, memaddr, t12, bool, i32, script0, _start, 5, 18, 0_wasm:opcode:call:before, true
1196, memaddr, t12, bool, i32, script0, _start, 5, 27, 0_wasm:opcode:call:before, true
1760, memaddr, t12, bool, i32, script0, _start, 5, 36, 0_wasm:opcode:call:before, true
2324, memaddr, t12, bool, i32, script0, _start, 5, 45, 0_wasm:opcode:call:before, true
2888, memaddr, t12, bool, i32, script0, _start, 5, 50, 0_wasm:opcode:call:before, true
3452, memaddr, t12, bool, i32, script0, _start, 5, 55, 0_wasm:opcode:call:before, true
4016, memaddr, t12, bool, i32, script0, _start, 5, 60, 0_wasm:opcode:call:before, true
4580, memaddr, t12, bool, i32, script0, _start, 5, 65, 0_wasm:opcode:call:before, true
448, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 9, 0_wasm:opcode:call:before, (1; (12; 13))
1012, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 18, 0_wasm:opcode:call:before, (1; (12; 13))
1576, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 27, 0_wasm:opcode:call:before, (1; (12; 13))
2140, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 36, 0_wasm:opcode:call:before, (1; (12; 13))
2704, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 45, 0_wasm:opcode:call:before, (1; (12; 13))
3268, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 50, 0_wasm:opcode:call:before, (1; (12; 13))
3832, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 55, 0_wasm:opcode:call:before, (1; (12; 13))
4396, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 60, 0_wasm:opcode:call:before, (1; (12; 13))
4960, memaddr, b, (i32,(i32,i32)), (i32; i32; i32), script0, _start, 5, 65, 0_wasm:opcode:call:before, (1; (12; 13))
328, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 9, 0_wasm:opcode:call:before, (0; 1; 2)
368, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 9, 0_wasm:opcode:call:before, (0; 1; 2)
408, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 9, 0_wasm:opcode:call:before, (0; 1; 2)
892, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 18, 0_wasm:opcode:call:before, (0; 1; 2)
932, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 18, 0_wasm:opcode:call:before, (0; 1; 2)
972, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 18, 0_wasm:opcode:call:before, (0; 1; 2)
1456, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 27, 0_wasm:opcode:call:before, (0; 1; 2)
1496, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 27, 0_wasm:opcode:call:before, (0; 1; 2)
1536, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 27, 0_wasm:opcode:call:before, (0; 1; 2)
2020, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 36, 0_wasm:opcode:call:before, (0; 1; 2)
2060, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 36, 0_wasm:opcode:call:before, (0; 1; 2)
2100, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 36, 0_wasm:opcode:call:before, (0; 1; 2)
2584, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 45, 0_wasm:opcode:call:before, (0; 1; 2)
2624, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 45, 0_wasm:opcode:call:before, (0; 1; 2)
2664, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 45, 0_wasm:opcode:call:before, (0; 1; 2)
3148, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 50, 0_wasm:opcode:call:before, (0; 1; 2)
3188, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 50, 0_wasm:opcode:call:before, (0; 1; 2)
3228, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 50, 0_wasm:opcode:call:before, (0; 1; 2)
3712, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 55, 0_wasm:opcode:call:before, (0; 1; 2)
3752, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 55, 0_wasm:opcode:call:before, (0; 1; 2)
3792, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 55, 0_wasm:opcode:call:before, (0; 1; 2)
4276, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 60, 0_wasm:opcode:call:before, (0; 1; 2)
4316, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 60, 0_wasm:opcode:call:before, (0; 1; 2)
4356, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 60, 0_wasm:opcode:call:before, (0; 1; 2)
4840, memaddr, t2, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 65, 0_wasm:opcode:call:before, (0; 1; 2)
4880, memaddr, t3, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 65, 0_wasm:opcode:call:before, (0; 1; 2)
4920, memaddr, t7, (i32,i32,i32), (i32; i32; i32), script0, _start, 5, 65, 0_wasm:opcode:call:before, (0; 1; 2)
292, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 9, 0_wasm:opcode:call:before, (0; 9)
856, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 18, 0_wasm:opcode:call:before, (1; 18)
1420, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 27, 0_wasm:opcode:call:before, (1; 27)
1984, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 36, 0_wasm:opcode:call:before, (3; 36)
2548, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 45, 0_wasm:opcode:call:before, (0; 45)
3112, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 50, 0_wasm:opcode:call:before, (1; 50)
3676, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 55, 0_wasm:opcode:call:before, (2; 55)
4240, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 60, 0_wasm:opcode:call:before, (0; 60)
4804, memaddr, bound1, (i32,u32), (i32; i32), script0, _start, 5, 65, 0_wasm:opcode:call:before, (0; 65)
182, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 9, 0_wasm:opcode:call:before, (-10; other str)
219, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 9, 0_wasm:opcode:call:before, (-5; wassup)
746, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 18, 0_wasm:opcode:call:before, (-10; other str)
783, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 18, 0_wasm:opcode:call:before, (-5; wassup)
1310, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 27, 0_wasm:opcode:call:before, (-10; other str)
1347, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 27, 0_wasm:opcode:call:before, (-5; wassup)
1874, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 36, 0_wasm:opcode:call:before, (-10; other str)
1911, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 36, 0_wasm:opcode:call:before, (-5; wassup)
2438, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 45, 0_wasm:opcode:call:before, (-10; other str)
2475, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 45, 0_wasm:opcode:call:before, (-5; wassup)
3002, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 50, 0_wasm:opcode:call:before, (-10; other str)
3039, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 50, 0_wasm:opcode:call:before, (-5; wassup)
3566, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 55, 0_wasm:opcode:call:before, (-10; other str)
3603, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 55, 0_wasm:opcode:call:before, (-5; wassup)
4130, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 60, 0_wasm:opcode:call:before, (-10; other str)
4167, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 60, 0_wasm:opcode:call:before, (-5; wassup)
4694, memaddr, t5, (i8,str), (i32; i32; i32), script0, _start, 5, 65, 0_wasm:opcode:call:before, (-10; other str)
4731, memaddr, t9, (i8,str), (i32; i32; i32), script0, _start, 5, 65, 0_wasm:opcode:call:before, (-5; wassup)
488, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 9, 0_wasm:opcode:call:before, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
528, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 9, 0_wasm:opcode:call:before, (wassup; +1.00018e3)
1052, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 18, 0_wasm:opcode:call:before, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
1092, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 18, 0_wasm:opcode:call:before, (wassup; +1.00018e3)
1616, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 27, 0_wasm:opcode:call:before, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
1656, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 27, 0_wasm:opcode:call:before, (wassup; +1.00018e3)
2180, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 36, 0_wasm:opcode:call:before, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
2220, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 36, 0_wasm:opcode:call:before, (wassup; +1.00018e3)
2744, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 45, 0_wasm:opcode:call:before, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
2784, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 45, 0_wasm:opcode:call:before, (wassup; +1.00018e3)
3308, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 50, 0_wasm:opcode:call:before, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
3348, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 50, 0_wasm:opcode:call:before, (wassup; +1.00018e3)
3872, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 55, 0_wasm:opcode:call:before, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
3912, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 55, 0_wasm:opcode:call:before, (wassup; +1.00018e3)
4436, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 60, 0_wasm:opcode:call:before, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
4476, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 60, 0_wasm:opcode:call:before, (wassup; +1.00018e3)
5000, memaddr, t6, (str,f32), (i32; i32; f32), script0, _start, 5, 65, 0_wasm:opcode:call:before, (BOOOOOOOOOOOOOOYAH; +1.00018e3)
5040, memaddr, t10, (str,f32), (i32; i32; f32), script0, _start, 5, 65, 0_wasm:opcode:call:before, (wassup; +1.00018e3)
256, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 9, 0_wasm:opcode:call:before, (5; 9)
820, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 18, 0_wasm:opcode:call:before, (5; 18)
1384, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 27, 0_wasm:opcode:call:before, (5; 27)
1948, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 36, 0_wasm:opcode:call:before, (5; 36)
2512, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 45, 0_wasm:opcode:call:before, (5; 45)
3076, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 50, 0_wasm:opcode:call:before, (5; 50)
3640, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 55, 0_wasm:opcode:call:before, (5; 55)
4204, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 60, 0_wasm:opcode:call:before, (5; 60)
4768, memaddr, bound0, (u32,u32), (i32; i32), script0, _start, 5, 65, 0_wasm:opcode:call:before, (5; 65)
100, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 9, 0_wasm:opcode:call:before, (0; 1; -2)
141, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 9, 0_wasm:opcode:call:before, (0; 1; 2)
664, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 18, 0_wasm:opcode:call:before, (0; 1; -2)
705, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 18, 0_wasm:opcode:call:before, (0; 1; 2)
1228, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 27, 0_wasm:opcode:call:before, (0; 1; -2)
1269, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 27, 0_wasm:opcode:call:before, (0; 1; 2)
1792, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 36, 0_wasm:opcode:call:before, (0; 1; -2)
1833, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 36, 0_wasm:opcode:call:before, (0; 1; 2)
2356, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 45, 0_wasm:opcode:call:before, (0; 1; -2)
2397, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 45, 0_wasm:opcode:call:before, (0; 1; 2)
2920, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 50, 0_wasm:opcode:call:before, (0; 1; -2)
2961, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 50, 0_wasm:opcode:call:before, (0; 1; 2)
3484, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 55, 0_wasm:opcode:call:before, (0; 1; -2)
3525, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 55, 0_wasm:opcode:call:before, (0; 1; 2)
4048, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 60, 0_wasm:opcode:call:before, (0; 1; -2)
4089, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 60, 0_wasm:opcode:call:before, (0; 1; 2)
4612, memaddr, t4, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 65, 0_wasm:opcode:call:before, (0; 1; -2)
4653, memaddr, t8, (u8,i32,i64), (i32; i32; i64), script0, _start, 5, 65, 0_wasm:opcode:call:before, (0; 1; 2)