================================= REPORT CSV FLUSH ====================================
id, id_type, name, whamm_type, wasm_type, script_id, fname, fid, pc, probe_id, value(s)
4, memaddr, length, u32, i32, script0, main, 5, 47, 0_wasm:opcode:drop:before, 27
232, memaddr, length, u32, i32, script0, main, 5, 52, 0_wasm:opcode:drop:before, 27
460, memaddr, length, u32, i32, script0, main, 5, 57, 0_wasm:opcode:drop:before, 27
688, memaddr, length, u32, i32, script0, main, 5, 62, 0_wasm:opcode:drop:before, 27
916, memaddr, length, u32, i32, script0, main, 5, 67, 0_wasm:opcode:drop:before, 27
36, memaddr, l, i32, i32, script0, main, 5, 47, 0_wasm:opcode:drop:before, 27
264, memaddr, l, i32, i32, script0, main, 5, 52, 0_wasm:opcode:drop:before, 27
492, memaddr, l, i32, i32, script0, main, 5, 57, 0_wasm:opcode:drop:before, 27
720, memaddr, l, i32, i32, script0, main, 5, 62, 0_wasm:opcode:drop:before, 27
948, memaddr, l, i32, i32, script0, main, 5, 67, 0_wasm:opcode:drop:before, 27
68, memaddr, start_exp_true, bool, i32, script0, main, 5, 47, 0_wasm:opcode:drop:before, true
100, memaddr, start_exp_false, bool, i32, script0, main, 5, 47, 0_wasm:opcode:drop:before, false
132, memaddr, end_exp_true, bool, i32, script0, main, 5, 47, 0_wasm:opcode:drop:before, true
164, memaddr, end_exp_false, bool, i32, script0, main, 5, 47, 0_wasm:opcode:drop:before, false
296, memaddr, start_exp_true, bool, i32, script0, main, 5, 52, 0_wasm:opcode:drop:before, true
328, memaddr, start_exp_false, bool, i32, script0, main, 5, 52, 0_wasm:opcode:drop:before, false
360, memaddr, end_exp_true, bool, i32, script0, main, 5, 52, 0_wasm:opcode:drop:before, true
392, memaddr, end_exp_false, bool, i32, script0, main, 5, 52, 0_wasm:opcode:drop:before, false
524, memaddr, start_exp_true, bool, i32, script0, main, 5, 57, 0_wasm:opcode:drop:before, true
556, memaddr, start_exp_false, bool, i32, script0, main, 5, 57, 0_wasm:opcode:drop:before, false
588, memaddr, end_exp_true, bool, i32, script0, main, 5, 57, 0_wasm:opcode:drop:before, true
620, memaddr, end_exp_false, bool, i32, script0, main, 5, 57, 0_wasm:opcode:drop:before, false
752, memaddr, start_exp_true, bool, i32, script0, main, 5, 62, 0_wasm:opcode:drop:before, true
784, memaddr, start_exp_false, bool, i32, script0, main, 5, 62, 0_wasm:opcode:drop:before, false
816, memaddr, end_exp_true, bool, i32, script0, main, 5, 62, 0_wasm:opcode:drop:before, true
848, memaddr, end_exp_false, bool, i32, script0, main, 5, 62, 0_wasm:opcode:drop:before, false
980, memaddr, start_exp_true, bool, i32, script0, main, 5, 67, 0_wasm:opcode:drop:before, true
1012, memaddr, start_exp_false, bool, i32, script0, main, 5, 67, 0_wasm:opcode:drop:before, false
1044, memaddr, end_exp_true, bool, i32, script0, main, 5, 67, 0_wasm:opcode:drop:before, true
1076, memaddr, end_exp_false, bool, i32, script0, main, 5, 67, 0_wasm:opcode:drop:before, false
196, memaddr, s, str, (i32; i32), script0, main, 5, 47, 0_wasm:opcode:drop:before, abcdefghijklmnopqrstuvwxyz

424, memaddr, s, str, (i32; i32), script0, main, 5, 52, 0_wasm:opcode:drop:before, abcdefghijklmnopqrstuvwxyz

652, memaddr, s, str, (i32; i32), script0, main, 5, 57, 0_wasm:opcode:drop:before, abcdefghijklmnopqrstuvwxyz

880, memaddr, s, str, (i32; i32), script0, main, 5, 62, 0_wasm:opcode:drop:before, abcdefghijklmnopqrstuvwxyz

1108, memaddr, s, str, (i32; i32), script0, main, 5, 67, 0_wasm:opcode:drop:before, abcdefghijklmnopqrstuvwxyz