================================= REPORT CSV FLUSH ====================================
id, id_type, name, whamm_type, wasm_type, script_id, fname, fid, pc, probe_id, value(s)
4, memaddr, num, i32, i32, script0, basic_br, 0, 1, 0_wasm:func:entry:<no-mode>, 1
36, memaddr, num, i32, i32, script0, if_stmt, 3, 1, 1_wasm:func:entry:<no-mode>, 2
68, memaddr, num, i32, i32, script0, if_stmt, 3, 1, 3_wasm:func:entry:<no-mode>, 4
100, memaddr, num, i32, i32, script0, select_stmt, 4, 1, 1_wasm:func:entry:<no-mode>, 2
132, memaddr, num, i32, i32, script0, select_stmt, 4, 1, 2_wasm:func:entry:<no-mode>, 3