================================= REPORT CSV FLUSH ====================================
id, id_type, name, whamm_type, wasm_type, script_id, fname, fid, pc, probe_id, value(s)
4, memaddr, l, u32, i32, script0, main, 5, 47, 0_wasm:opcode:drop:before, 11
328, memaddr, l, u32, i32, script0, main, 5, 52, 0_wasm:opcode:drop:before, 11
652, memaddr, l, u32, i32, script0, main, 5, 57, 0_wasm:opcode:drop:before, 11
976, memaddr, l, u32, i32, script0, main, 5, 62, 0_wasm:opcode:drop:before, 11
1300, memaddr, l, u32, i32, script0, main, 5, 67, 0_wasm:opcode:drop:before, 11
36, memaddr, start_exp_true, bool, i32, script0, main, 5, 47, 0_wasm:opcode:drop:before, true
68, memaddr, start_exp_false, bool, i32, script0, main, 5, 47, 0_wasm:opcode:drop:before, false
100, memaddr, end_exp_true, bool, i32, script0, main, 5, 47, 0_wasm:opcode:drop:before, true
132, memaddr, end_exp_false, bool, i32, script0, main, 5, 47, 0_wasm:opcode:drop:before, false
164, memaddr, contains_exp_true0, bool, i32, script0, main, 5, 47, 0_wasm:opcode:drop:before, true
196, memaddr, contains_exp_true1, bool, i32, script0, main, 5, 47, 0_wasm:opcode:drop:before, true
228, memaddr, contains_exp_true2, bool, i32, script0, main, 5, 47, 0_wasm:opcode:drop:before, true
260, memaddr, contains_exp_false, bool, i32, script0, main, 5, 47, 0_wasm:opcode:drop:before, false
360, memaddr, start_exp_true, bool, i32, script0, main, 5, 52, 0_wasm:opcode:drop:before, true
392, memaddr, start_exp_false, bool, i32, script0, main, 5, 52, 0_wasm:opcode:drop:before, false
424, memaddr, end_exp_true, bool, i32, script0, main, 5, 52, 0_wasm:opcode:drop:before, true
456, memaddr, end_exp_false, bool, i32, script0, main, 5, 52, 0_wasm:opcode:drop:before, false
488, memaddr, contains_exp_true0, bool, i32, script0, main, 5, 52, 0_wasm:opcode:drop:before, true
520, memaddr, contains_exp_true1, bool, i32, script0, main, 5, 52, 0_wasm:opcode:drop:before, true
552, memaddr, contains_exp_true2, bool, i32, script0, main, 5, 52, 0_wasm:opcode:drop:before, true
584, memaddr, contains_exp_false, bool, i32, script0, main, 5, 52, 0_wasm:opcode:drop:before, false
684, memaddr, start_exp_true, bool, i32, script0, main, 5, 57, 0_wasm:opcode:drop:before, true
716, memaddr, start_exp_false, bool, i32, script0, main, 5, 57, 0_wasm:opcode:drop:before, false
748, memaddr, end_exp_true, bool, i32, script0, main, 5, 57, 0_wasm:opcode:drop:before, true
780, memaddr, end_exp_false, bool, i32, script0, main, 5, 57, 0_wasm:opcode:drop:before, false
812, memaddr, contains_exp_true0, bool, i32, script0, main, 5, 57, 0_wasm:opcode:drop:before, true
844, memaddr, contains_exp_true1, bool, i32, script0, main, 5, 57, 0_wasm:opcode:drop:before, true
876, memaddr, contains_exp_true2, bool, i32, script0, main, 5, 57, 0_wasm:opcode:drop:before, true
908, memaddr, contains_exp_false, bool, i32, script0, main, 5, 57, 0_wasm:opcode:drop:before, false
1008, memaddr, start_exp_true, bool, i32, script0, main, 5, 62, 0_wasm:opcode:drop:before, true
1040, memaddr, start_exp_false, bool, i32, script0, main, 5, 62, 0_wasm:opcode:drop:before, false
1072, memaddr, end_exp_true, bool, i32, script0, main, 5, 62, 0_wasm:opcode:drop:before, true
1104, memaddr, end_exp_false, bool, i32, script0, main, 5, 62, 0_wasm:opcode:drop:before, false
1136, memaddr, contains_exp_true0, bool, i32, script0, main, 5, 62, 0_wasm:opcode:drop:before, true
1168, memaddr, contains_exp_true1, bool, i32, script0, main, 5, 62, 0_wasm:opcode:drop:before, true
1200, memaddr, contains_exp_true2, bool, i32, script0, main, 5, 62, 0_wasm:opcode:drop:before, true
1232, memaddr, contains_exp_false, bool, i32, script0, main, 5, 62, 0_wasm:opcode:drop:before, false
1332, memaddr, start_exp_true, bool, i32, script0, main, 5, 67, 0_wasm:opcode:drop:before, true
1364, memaddr, start_exp_false, bool, i32, script0, main, 5, 67, 0_wasm:opcode:drop:before, false
1396, memaddr, end_exp_true, bool, i32, script0, main, 5, 67, 0_wasm:opcode:drop:before, true
1428, memaddr, end_exp_false, bool, i32, script0, main, 5, 67, 0_wasm:opcode:drop:before, false
1460, memaddr, contains_exp_true0, bool, i32, script0, main, 5, 67, 0_wasm:opcode:drop:before, true
1492, memaddr, contains_exp_true1, bool, i32, script0, main, 5, 67, 0_wasm:opcode:drop:before, true
1524, memaddr, contains_exp_true2, bool, i32, script0, main, 5, 67, 0_wasm:opcode:drop:before, true
1556, memaddr, contains_exp_false, bool, i32, script0, main, 5, 67, 0_wasm:opcode:drop:before, false
292, memaddr, s, str, (i32, i32), script0, main, 5, 47, 0_wasm:opcode:drop:before, hello world
616, memaddr, s, str, (i32, i32), script0, main, 5, 52, 0_wasm:opcode:drop:before, hello world
940, memaddr, s, str, (i32, i32), script0, main, 5, 57, 0_wasm:opcode:drop:before, hello world
1264, memaddr, s, str, (i32, i32), script0, main, 5, 62, 0_wasm:opcode:drop:before, hello world
1588, memaddr, s, str, (i32, i32), script0, main, 5, 67, 0_wasm:opcode:drop:before, hello world