================================= REPORT CSV FLUSH ====================================
id, id_type, name, whamm_type, wasm_type, script_id, fname, fid, pc, probe_id, value(s)
4, memaddr, a, i32, i32, script0, #2, 2, 5, 0_wasm:opcode:call:before, 2
36, memaddr, b, i32, i32, script0, #2, 2, 5, 0_wasm:opcode:call:before, 1
68, memaddr, b, i32, i32, script0, #2, 2, 11, 0_wasm:opcode:call:before, 3
100, memaddr, a, i64, i64, script0, #2, 2, 11, 0_wasm:opcode:call:before, 4
