============================= REPORT CSV FLUSH ================================
id, id_type, name, whamm_type, wasm_type, script_id, fid:pc, probe_id, value(s)
3, global_id, taken, i32, i32, script0, 0:5, 1_wasm:opcode:br_if:before, 0
4, global_id, not_taken, i32, i32, script0, 0:5, 1_wasm:opcode:br_if:before, 1
5, global_id, taken, i32, i32, script0, 0:6, 0_wasm:opcode:br:before, 1
6, global_id, taken, i32, i32, script0, 1:6, 1_wasm:opcode:br_if:before, 1
7, global_id, not_taken, i32, i32, script0, 1:6, 1_wasm:opcode:br_if:before, 3
8, global_id, taken, i32, i32, script0, 1:10, 1_wasm:opcode:br_if:before, 1
9, global_id, not_taken, i32, i32, script0, 1:10, 1_wasm:opcode:br_if:before, 2
10, global_id, taken, i32, i32, script0, 1:11, 0_wasm:opcode:br:before, 2