==== CALC ====
calc(9, 0) -> 9
calc(8, 1) -> 9
calc(7, 2) -> 9
calc(6, 3) -> 9
calc(5, 4) -> 20
calc(4, 5) -> 20
calc(3, 6) -> 18
calc(2, 7) -> 14
calc(1, 8) -> 8
calc(0, 9) -> 0

==== PRINT_X ====
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!

============================= REPORT CSV FLUSH ================================
id, id_type, name, whamm_type, wasm_type, script_id, fid:pc, probe_id, value(s)
3, global_id, taken, i32, i32, script0, 38:36, 1_wasm:opcode:br_if:before, 4
4, global_id, not_taken, i32, i32, script0, 38:36, 1_wasm:opcode:br_if:before, 6
5, global_id, taken, i32, i32, script0, 38:76, 1_wasm:opcode:br_if:before, 0
6, global_id, not_taken, i32, i32, script0, 38:76, 1_wasm:opcode:br_if:before, 6
7, global_id, taken, i32, i32, script0, 38:77, 0_wasm:opcode:br:before, 6
8, global_id, taken, i32, i32, script0, 38:104, 1_wasm:opcode:br_if:before, 0
9, global_id, not_taken, i32, i32, script0, 38:104, 1_wasm:opcode:br_if:before, 4
10, global_id, taken, i32, i32, script0, 38:105, 0_wasm:opcode:br:before, 4
11, global_id, taken, i32, i32, script0, 38:110, 0_wasm:opcode:br:before, 6
12, global_id, taken, i32, i32, script0, 38:121, 0_wasm:opcode:br:before, 4
13, global_id, taken, i32, i32, script0, 39:76, 1_wasm:opcode:br_if:before, 10
14, global_id, not_taken, i32, i32, script0, 39:76, 1_wasm:opcode:br_if:before, 1
15, global_id, taken, i32, i32, script0, 39:152, 0_wasm:opcode:br:before, 10
