============================= REPORT CSV FLUSH ================================
id, id_type, name, whamm_type, wasm_type, script_id, fid:pc, probe_id, value(s)
238, memaddr, taken, i32, i32, script0, 0:10, 1_wasm:opcode:br_if, 0
265, memaddr, not_taken, i32, i32, script0, 0:10, 1_wasm:opcode:br_if, 1
292, memaddr, taken, i32, i32, script0, 0:12, 0_wasm:opcode:br, 1
319, memaddr, taken, i32, i32, script0, 1:12, 1_wasm:opcode:br_if, 1
346, memaddr, not_taken, i32, i32, script0, 1:12, 1_wasm:opcode:br_if, 3
373, memaddr, taken, i32, i32, script0, 1:19, 1_wasm:opcode:br_if, 1
400, memaddr, not_taken, i32, i32, script0, 1:19, 1_wasm:opcode:br_if, 2
427, memaddr, taken, i32, i32, script0, 1:21, 0_wasm:opcode:br, 2