==== CALC ====
calc(9, 0) -> 9
calc(8, 1) -> 9
calc(7, 2) -> 9
calc(6, 3) -> 9
calc(5, 4) -> 20
calc(4, 5) -> 20
calc(3, 6) -> 18
calc(2, 7) -> 14
calc(1, 8) -> 8
calc(0, 9) -> 0

==== PRINT ====
hi world!
hi world!
hi world!
hi world!
hi world!
hi world!
hi world!
hi world!
hi world!
hi world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
'sup world!
'sup world!
'sup world!
'sup world!
'sup world!
'sup world!
'sup world!
'sup world!
'sup world!
'sup world!

================================= REPORT CSV FLUSH ====================================
id, id_type, name, whamm_type, wasm_type, script_id, fname, fid, pc, probe_id, value(s)
4, memaddr, taken, i32, i32, script0, calc, 27, 88, 1_wasm:opcode:br_if:before, 4
36, memaddr, not_taken, i32, i32, script0, calc, 27, 88, 1_wasm:opcode:br_if:before, 6
68, memaddr, taken, i32, i32, script0, calc, 27, 159, 1_wasm:opcode:br_if:before, 0
100, memaddr, not_taken, i32, i32, script0, calc, 27, 159, 1_wasm:opcode:br_if:before, 6
132, memaddr, taken, i32, i32, script0, calc, 27, 161, 0_wasm:opcode:br:before, 6
164, memaddr, taken, i32, i32, script0, calc, 27, 209, 1_wasm:opcode:br_if:before, 0
196, memaddr, not_taken, i32, i32, script0, calc, 27, 209, 1_wasm:opcode:br_if:before, 4
228, memaddr, taken, i32, i32, script0, calc, 27, 211, 0_wasm:opcode:br:before, 4
260, memaddr, taken, i32, i32, script0, calc, 27, 221, 0_wasm:opcode:br:before, 6
292, memaddr, taken, i32, i32, script0, calc, 27, 245, 0_wasm:opcode:br:before, 4
324, memaddr, taken, i32, i32, script0, print_x, 28, 154, 1_wasm:opcode:br_if:before, 30
356, memaddr, not_taken, i32, i32, script0, print_x, 28, 154, 1_wasm:opcode:br_if:before, 3
388, memaddr, taken, i32, i32, script0, print_x, 28, 408, 0_wasm:opcode:br:before, 30
452, memaddr, taken, i32, i32, script0, opt_str, 29, 72, 0_wasm:opcode:br:before, 10
484, memaddr, taken, i32, i32, script0, opt_str, 29, 94, 0_wasm:opcode:br:before, 10
420, memaddr, taken_branches, map<u32,u32>, i32, script0, opt_str, 29, 46, 2_wasm:opcode:br_table:before, 0->10;1->10;2->10