================================= REPORT CSV FLUSH ====================================
id, id_type, name, whamm_type, wasm_type, script_id, fname, fid, pc, probe_id, value(s)
4, memaddr, page0, u32, i32, script0, #0, 0, 1, 0_wasm:opcode:memory.size:before, 1
36, memaddr, page1, u32, i32, script0, #0, 0, 1, 0_wasm:opcode:memory.size:before, 1
68, memaddr, mem1, u32, i32, script0, #0, 0, 1, 0_wasm:opcode:memory.size:before, 1
100, memaddr, page0, u32, i32, script0, #0, 0, 9, 0_wasm:opcode:memory.size:before, 1
132, memaddr, page1, u32, i32, script0, #0, 0, 9, 0_wasm:opcode:memory.size:before, 1
164, memaddr, mem1, u32, i32, script0, #0, 0, 9, 0_wasm:opcode:memory.size:before, 2
196, memaddr, page0, u32, i32, script0, #0, 0, 17, 0_wasm:opcode:memory.size:before, 1
228, memaddr, page1, u32, i32, script0, #0, 0, 17, 0_wasm:opcode:memory.size:before, 1
260, memaddr, mem1, u32, i32, script0, #0, 0, 17, 0_wasm:opcode:memory.size:before, 6