// TODO -- i think the output here is wrong (should be fewer matches?)
================================= REPORT CSV FLUSH ====================================
id, id_type, name, whamm_type, wasm_type, script_id, fname, fid, pc, probe_id, value(s)
4, memaddr, val, i32, i32, script0, main, 0, 0, 52_wasm:opcode:i64.const:before, 0
36, memaddr, val, i32, i32, script0, main, 0, 1, 41_wasm:opcode:i64.store:before, 0
68, memaddr, val, i32, i32, script0, main, 0, 2, 51_wasm:opcode:i32.const:before, 0
100, memaddr, val, i32, i32, script0, main, 0, 3, 26_wasm:opcode:i32.load:before, 0
132, memaddr, val, i32, i32, script0, main, 0, 4, 26_wasm:opcode:i32.load:before, 0
164, memaddr, val, i32, i32, script0, main, 0, 16, 18_wasm:opcode:drop:before, 0
196, memaddr, val, i32, i32, script0, main, 0, 17, 9_wasm:opcode:end:before, 0