================================= REPORT CSV FLUSH ====================================
id, id_type, name, whamm_type, wasm_type, script_id, fname, fid, pc, probe_id, value(s)
4, memaddr, val, i32, i32, script0, main, 0, 3, 52_wasm:opcode:i64.const:before, 0
36, memaddr, val, i32, i32, script0, main, 0, 8, 51_wasm:opcode:i32.const:before, 0
68, memaddr, val, i32, i32, script0, main, 0, 13, 26_wasm:opcode:i32.load:before, 0
100, memaddr, val, i32, i32, script0, main, 0, 17, 9_wasm:opcode:end:before, 0