============================= REPORT CSV FLUSH ================================
id, id_type, name, whamm_type, wasm_type, script_id, fid:pc, probe_id, value(s)
3, global_id, count, u32, i32, script0, 5:1, 0_wasm:opcode:call:before, 1
4, global_id, count, u32, i32, script0, 5:4, 0_wasm:opcode:call:before, 1
5, global_id, count, u32, i32, script0, 5:9, 0_wasm:opcode:call:before, 0
6, global_id, count, u32, i32, script0, 5:14, 0_wasm:opcode:call:before, 0
7, global_id, count, u32, i32, script0, 5:19, 0_wasm:opcode:call:before, 0
8, global_id, count, u32, i32, script0, 5:24, 0_wasm:opcode:call:before, 1
9, global_id, count, u32, i32, script0, 5:27, 0_wasm:opcode:call:before, 0
10, global_id, count, u32, i32, script0, 5:30, 0_wasm:opcode:call:before, 0
11, global_id, count, u32, i32, script0, 5:33, 0_wasm:opcode:call:before, 1
12, global_id, count, u32, i32, script0, 5:36, 0_wasm:opcode:call:before, 1