============================= REPORT CSV FLUSH ================================
id, id_type, name, whamm_type, wasm_type, script_id, fid:pc, probe_id, value(s)
4, memaddr, count, u32, i32, script0, 5:4, 0_wasm:opcode:call:before, 1
31, memaddr, count, u32, i32, script0, 5:9, 0_wasm:opcode:call:before, 0
58, memaddr, count, u32, i32, script0, 5:14, 0_wasm:opcode:call:before, 0
85, memaddr, count, u32, i32, script0, 5:19, 0_wasm:opcode:call:before, 0
112, memaddr, count, u32, i32, script0, 5:24, 0_wasm:opcode:call:before, 1
139, memaddr, count, u32, i32, script0, 5:27, 0_wasm:opcode:call:before, 0
166, memaddr, count, u32, i32, script0, 5:30, 0_wasm:opcode:call:before, 0
193, memaddr, count, u32, i32, script0, 5:33, 0_wasm:opcode:call:before, 1
220, memaddr, count, u32, i32, script0, 5:36, 0_wasm:opcode:call:before, 1