==== CALC ====
calc(9, 0) -> 9
calc(8, 1) -> 9
calc(7, 2) -> 9
calc(6, 3) -> 9
calc(5, 4) -> 20
calc(4, 5) -> 20
calc(3, 6) -> 18
calc(2, 7) -> 14
calc(1, 8) -> 8
calc(0, 9) -> 0

==== PRINT_X ====
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!

============================= REPORT CSV FLUSH ================================
id, id_type, name, whamm_type, wasm_type, script_id, fid:pc, probe_id, value(s)
3, global_id, count, u32, i32, script0, 40:253, 0_wasm:opcode:call:before, 1
4, global_id, count, u32, i32, script0, 40:284, 0_wasm:opcode:call:before, 10